[project]
name = "audit-inquiry-automation"
version = "0.1.0"
description = ""
authors = [
    {name = "PDW-Accountant",email = "kkk273@naver.com"}
]

license = {text = "DONGTAN 91-DONG WELFARE CENTER"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "tesseract (>=0.1.3,<0.2.0)",
    "opencv-python (>=4.13.0.92,<5.0.0.0)",
    "pytest (>=9.0.2,<10.0.0)",
    "pdfplumber (>=0.11.9,<0.12.0)"
]

[tool.poetry]   # poetry에서 사용하는 특수한 기능에 대한 정의 모음
# 배포용 패키지가 아니라 단순 실행용 프로젝트
package-mode = false    # 가상환경에 패키지로 등록하지 않도록 false를 명시

[dependency-groups]
dev = [
    "streamlit (>=1.54.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
